secretGenerator:                      # Passwortspeicher mit Passwort
- name: mysql-pass
  literals:
  - password=mysqlpassword
resources:                            # Starten der Deployments
- persistentvolume.yaml
- mysql-deployment.yaml
- wordpress-deployment.yaml